OC.L10N.register(
    "context_chat",
    {
    "Deleted file" : "Fichier supprimé",
    "Prompt" : "Prompt",
    "Search your documents, files and more" : "Recherchez vos documents, vos fichiers et bien plus",
    "Max result number" : "Nombre maximal de résultats",
    "Sources" : "Sources",
    "Context Chat" : "Chat contextuel",
    "Ask a question about your data." : "Poser une question à propos de vos données.",
    "Generated response" : "Réponse générée",
    "The text generated by the model" : "Texte généré par le modèle",
    "never" : "jamais",
    "{time} ago" : "il y a {time}",
    "Indexing Status" : "Statut de l'indexation",
    "Content provider" : "Fournisseur de contenu",
    "Download Logs" : "Télécharger les journaux",
    "Official documentation" : "Documentation officielle",
    "_({count} new file)_::_({count} new files)_" : ["({count} nouveau fichier)","({count} nouveaux fichiers)","({count} nouveaux fichiers)"]
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
