OC.L10N.register(
    "context_chat",
    {
    "Deleted file" : "File eliminato",
    "Prompt" : "Prompt",
    "list of providers" : "lista di fornitori",
    "Max result number" : "Numero massimo di risultati",
    "Sources" : "Sorgenti",
    "Context Chat" : "Chat contestual",
    "Ask a question about your data." : "Poni una domanda sui tuoi dati.",
    "Ask a question about your documents, files and more" : "Poni una domanda riguardo i tuoi documenti, files ed altro",
    "list of sources or providers" : "lista di fonti o fornitori",
    "Generated response" : "Risposta generata",
    "The text generated by the model" : "Il testo generato dal modello",
    "Nextcloud Assistant Context Chat" : "Chat con l'assistente contestuale di Nextcloud",
    "Chat with your documents" : "Chatta con i tuoi documenti",
    "never" : "mai",
    "{time} ago" : "{time} fa"
},
"nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
