<?php

declare(strict_types=1);

/**
 * @copyright Copyright (c) 2023 Julien Veyssier <julien-nc@posteo.net>
 *
 * @author Julien Veyssier <julien-nc@posteo.net>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

namespace OCA\ContextChat\TaskProcessing;

use OCA\ContextChat\AppInfo\Application;
use OCP\IL10N;
use OCP\TaskProcessing\EShapeType;
use OCP\TaskProcessing\ITaskType;
use OCP\TaskProcessing\ShapeDescriptor;

class ContextChatTaskType implements ITaskType {
	public const ID = Application::APP_ID . ':context_chat';

	public function __construct(
		private IL10N $l,
	) {
	}

	/**
	 * @inheritDoc
	 * @since 2.3.0
	 */
	public function getName(): string {
		return $this->l->t('Context Chat');
	}

	/**
	 * @inheritDoc
	 * @since 2.3.0
	 */
	public function getDescription(): string {
		return $this->l->t('Ask a question about your data.');
	}

	/**
	 * @return string
	 * @since 2.3.0
	 */
	public function getId(): string {
		return self::ID;
	}

	/**
	 * @return ShapeDescriptor[]
	 * @since 2.3.0
	 */
	public function getInputShape(): array {
		return [
			'prompt' => new ShapeDescriptor(
				$this->l->t('Prompt'),
				$this->l->t('The prompt to work on'),
				EShapeType::Text,
			),
			'scopeType' => new ShapeDescriptor(
				$this->l->t('Scope type'),
				$this->l->t('none, source, provider'),
				EShapeType::Text,
			),
			'scopeList' => new ShapeDescriptor(
				$this->l->t('Scope list'),
				$this->l->t('list of sources or providers'),
				EShapeType::ListOfTexts,
			),
			'scopeListMeta' => new ShapeDescriptor(
				$this->l->t('Scope list metadata'),
				$this->l->t('Required to nicely render the scope list in assistant'),
				EShapeType::Text,
			),
		];
	}

	/**
	 * @return ShapeDescriptor[]
	 * @since 2.3.0
	 */
	public function getOutputShape(): array {
		return [
			'output' => new ShapeDescriptor(
				$this->l->t('Generated response'),
				$this->l->t('The text generated by the model'),
				EShapeType::Text,
			),
			'sources' => new ShapeDescriptor(
				$this->l->t('Sources referenced to generate the above response'),
				$this->l->t('The list of sources used to generate the output'),
				EShapeType::ListOfTexts,
			),
		];
	}
}
